### ISSUE TITLE
GenAI API Integration Articles/Tutorials Updation in Readme

### ISSUE THREAD

**Issue by MavSneha** [foss42/awesome-generative-ai-apis#11]
Updating the Readme.md with links that direct to articles that talk about GenAI API Integration and their Application.

I would like to work on this Under GSSOC ' 24 as a Contributor
Please Assign it to me.
@ashitaprasad

**Comment by ashitaprasad** [comment]
Sure you can send a PR

**Comment by MavSneha** [comment]
@ashitaprasad Ma'am I already made a PR request on which you updated me accordingly.

PR Link : https://github.com/foss42/awesome-generative-ai-apis/pull/10#event-12774927419

Please clear the following doubts of mine :
1. Is this issue assigned to me as I can't see an assigned tag.
2. Under which level will it be considered.

**Comment by ashitaprasad** [comment]
done
