### ISSUE TITLE
Adding SummarizeBot AI API to the readme file

### ISSUE THREAD

**Issue by sarayusreeyadavpadala** [foss42/awesome-generative-ai-apis#113]
SummarizeBot's AI API provides advanced text, audio, and image summarization, keyword extraction, and sentiment analysis across multiple languages. It uses machine learning, natural language processing, and blockchain technologies to deliver precise and efficient information extraction from various document formats​.

@ashitaprasad I would like to contribute to this repository by adding SummarizeBot AI API. Could you please assign this issue to me?

**Comment by ashitaprasad** [comment]
Closing as no PR.

**Comment by sarayusreeyadavpadala** [comment]
> Closing as no PR.

I have already made PR on this issue. Kindly check once.
