### ISSUE TITLE
Adding kairos API

### ISSUE THREAD

**Issue by AkhilYadavPadala** [foss42/awesome-generative-ai-apis#114]
The Kairos API is a cloud-based facial recognition and analysis service that provides tools for detecting faces, recognizing identities, and analyzing attributes like emotions, age, and gender. It offers easy integration via RESTful endpoints.
Kindly, assign this issue with gssoc tag @ashitaprasad

**Comment by ashitaprasad** [comment]
Not a Gen AI API.
