### ISSUE TITLE
Adding Google Gemma API

### ISSUE THREAD

**Issue by r7projects-shayan** [foss42/awesome-generative-ai-apis#116]
## Issue Description 

Currently the list does not have the famous Google Gemma API and the docs. 

## Solutions

Add the Google Gemma API and the docs to the list

## Program 

Gssoc 24

**Comment by r7projects-shayan** [comment]
@ashitaprasad Kindly assign this issue to me so that i can start working on it

**Comment by r7projects-shayan** [comment]
Hey @ashitaprasad , while researching I found out that Google Palm Model has been deprecated on February 15th, 2024. So I'm Adding the newest model Google Gemma instead

**Comment by ashitaprasad** [comment]
You need to add an API not a model.
