### ISSUE TITLE
[GSSoC'24] [Documentation] Enhancing README.md for Clarity and Professionalism

### ISSUE THREAD

**Issue by CoderUzumaki** [foss42/awesome-generative-ai-apis#12]
I've noticed that the current README.md file for our project could benefit from some improvements to enhance clarity, professionalism, and overall appeal. My goal is to make the README.md more informative, engaging, and error-free to provide a better understanding of the project to visitors and potential contributors.

**Measures:**

> 1. **Including Contribution Guidelines**: I'll add a section outlining how contributors can get involved, submit pull requests, and contribute effectively to the project.
> 2. **Adding YouTube Links wherever necessary**: I'll add YouTube video link, Title, Summary under "GenAI API Integration Youtube Videos" heading, which is currently left blank.
> 3. **Improving Formatting and Styling**: To enhance readability, I'll update the formatting, add relevant headings, and improve the overall visual appeal of the Readme.md file.
> 4. **Adding Usage Instructions**: Clear instructions on how to use Awesome Generative AI will be included.

I anticipate completing these improvements within given timeline. This effort aims to make Awesome Generative AI more welcoming to newcomers and provide a polished representation of our project to the community.

@ashitaprasad I request you to assign this issue to me under **GSSoC 2024**, so that I can start working on this.

Thank you for considering my request. I'm looking forward to making a meaningful contribution to the project.

**Comment by ashitaprasad** [comment]
Please go through the contributing guidelines and raise a valid issue & PR.

**Comment by CoderUzumaki** [comment]
> Please go through the contributing guidelines and raise a valid issue & PR.

Mam, 
I did indeed read the contributing guidelines and I do have few doubts-
1. Am I expected to directly fork the repo, make changes and raise a PR? if yes am i going to get the points for GSSoC?
2. I am not able detect why this issue is invalid, "[GSSoC'24] [Documentation]" because of this in the title or is there something else, please specify.

**Comment by ashitaprasad** [comment]
@CoderUzumaki raise an issue with what you are going to add. I will assign it to you and send a PR adding the items.
You will get the points.
