### ISSUE TITLE
Add information about Microsoft Azure Cognitive Services API

### ISSUE THREAD

**Issue by ananyag309** [foss42/awesome-generative-ai-apis#149]
Microsoft Azure Cognitive Services provide various AI APIs for vision, speech, language, and decision-making, enabling developers to integrate AI capabilities into their applications. @ashitaprasad please assign this issue to me under gssoc

**Comment by aditya1492025** [comment]
Microsoft Azure Cognitive Services API offers a range of AI tools for vision, speech, language, and decision-making tasks, enabling developers to integrate advanced, intelligent features into their applications easily. Key components include Vision API for image analysis, Speech API for speech recognition and synthesis, Language API for natural language processing, and Decision API for smart decision-making.
@ashitaprasad please assign this  issue to me under gssoc
