### ISSUE TITLE
GenAI API Integration YouTube Videos/Tutorials Updation in Readme

### ISSUE THREAD

**Issue by CoderUzumaki** [foss42/awesome-generative-ai-apis#19]
Updating the Readme.md with links that direct to YouTube videos that talk about GenAI API, their Integration and their Application.

I would like to work on this Under GSSOC ' 24 as a Contributor
Please Assign it to me.
@ashitaprasad

**Comment by Avishek8136** [comment]
Updating the Readme.md with links to YouTube videos helping with GenAI API, their Integration and their Application.
I would like to work on this Under GSSOC ' 24 as a Contributor
Please Assign it to me.
Also, Please Label it as GSSoC

**Comment by ashitaprasad** [comment]
@Avishek8136 You have to open a new issue when you want to add anything which will be assigned to you.
