### ISSUE TITLE
Improving the README.md file

### ISSUE THREAD

**Issue by SaileePhal** [foss42/awesome-generative-ai-apis#39]
Hello! I'm a beginner participating in GSSoC'24, and I'd like to contribute to the project by adding useful videos to the README.md file. These videos will help beginners learn how to build Generative AI models.

@ashitaprasad, could you please assign this issue to me?

Thank you!

**Comment by ashitaprasad** [comment]
Please read the contributing guide properly to understand what needs to be done.
