### ISSUE TITLE
Granite Foundationals Models by IBM

### ISSUE THREAD

**Issue by Raghucharan16** [foss42/awesome-generative-ai-apis#45]
Granite series of decoder-only code models for code generative tasks (e.g., fixing bugs, explaining code, documenting code), trained with code written in 116 programming languages. A comprehensive evaluation of the Granite Code model family on diverse tasks demonstrates that our models consistently reach state-of-the-art performance among available open source code LLMs. Further Details and API building using these models will be added

**Comment by ashitaprasad** [comment]
Closing due to no PR.

**Comment by Raghucharan16** [comment]
> Closing due to no PR.

Please reopen thisassign the labels and review it and merge #99
