### ISSUE TITLE
Adding IBM Watson AI API to the readme file

### ISSUE THREAD

**Issue by sarayusreeyadavpadala** [foss42/awesome-generative-ai-apis#84]
IBM Watson AI API provides a suite of tools and services that leverage artificial intelligence to analyze data, build applications, and improve business processes. Key features include natural language processing, machine learning, computer vision, and speech recognition. These APIs enable developers to integrate AI capabilities into their applications, offering functionalities such as chatbot creation, language translation, and sentiment analysis.

@ashitaprasad I would like to contribute to this repository by adding IBM Watson AI API to the readme file. Could you please assign me this issue?

**Comment by ashitaprasad** [comment]
PR already merged.
