### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by suhanipaliwal** [foss42/awesome-generative-ai-apis#9]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me under GSSOC'24

**Comment by ashitaprasad** [comment]
Done.
Also, read the contributing guide - https://github.com/foss42/awesome-generative-ai-apis/blob/main/CONTRIBUTING.md
We do not accept any issues/PRs outside the current scope.
