### ISSUE TITLE
GenAI API Integration Article Addition in Readme.md

### ISSUE THREAD

**Issue by Antiquely3059** [foss42/awesome-generative-ai-apis#95]
I want to add an article about how to use Gemini Python API and its various functions to build AI-enabled applications for free.
Can I go ahead ?

**Comment by ashitaprasad** [comment]
API is already present in the list.

**Comment by Antiquely3059** [comment]
I want to add article about Gemini API

**Comment by ashitaprasad** [comment]
Sure, go ahead and add the article.

**Comment by Vivekkaspa** [comment]
@ashitaprasad I would like to add a article which is actually a tutorial regarding Generative AI API Integration with LangChain. In my perspective,  LangChain framework to be added into the curated list as well especially while building applicaions based on LLMs. please assign me this issue to work on.

**Comment by ashitaprasad** [comment]
@Vivekkaspa Please raise a new issue.

**Comment by Vivekkaspa** [comment]
@ashitaprasad , Sure.
